# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15ad02c10be05bdba0a586f763636ed5d90bd9fca4dd6f00d244d57b76951db82b3be34b254a88be93e92ef7c33e2ba3cdbb3726e8621dd099c02afd093e4c44

test:
  secret_key_base: 17e15770ecd6f51db30159a518264f4ee30dc462a70327e6badca38706a5ea1220d3615b6ccda6d0920535d28bc3ae415632b7634a1ab721983076cab15f5fdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
